---
# tasks file for ansible-tinc (Ubuntu specific)

- name: Install tinc packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: tinc_packages
  tags: tinc

- name: Create tinc defaults file
  template: >
    src=tinc.default.j2
    dest=/etc/default/tinc
    owner=root
    group=root
    mode=0644
  tags: tinc
